[package]
name = "raycaster"
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
image = "*"

[dependencies.quicksilver]
version = "0.3.18"
features = []

[dependencies.specs]
version = "0.15.0"
features = []
