name: Main

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: tomaka/cargo-web:latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Cache cargo registry
      uses: actions/cache@v1
      with:
        path: ~/.cargo/registry
        key: cargo-registry-${{ hashFiles('**/Cargo.lock') }}

    - name: Cache cargo index
      uses: actions/cache@v1
      with:
        path: ~/.cargo/git
        key: cargo-index-${{ hashFiles('**/Cargo.lock') }}

    - name: Cache cargo build
      uses: actions/cache@v1
      with:
        path: target
        key: cargo-build-target-${{ hashFiles('**/Cargo.lock') }}

    - name: Test
      run: |
        rustc --version
        cargo --version
        cargo test --all --verbose
    - name: Build
      run: |
        cargo web --version
        cargo web deploy --release -o public
    - name: Upload public
      uses: actions/upload-artifact@v1
      with:
        name: public
        path: public

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download public
      uses: actions/download-artifact@v1
      with:
        name: public

    - name: Deploy
      working-directory: public
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git init
        git add .
        git commit -m "${GITHUB_SHA}"
        git push -f https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY master:gh-pages
